sudo: required
services:
    - docker

before_install:
  - docker build -t sinusekhar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sinusekhar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker-env"
  env: "DockerEnv-env"
  bucket_name: "elasticbeanstalk-us-west-2-518225494279"
  bucket_path: "Docker-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  
